### ISSUE TITLE
Excess modules

### ISSUE THREAD

**Issue by Thinstation** [emutex/ubilinux-kernel#2]
Have you considered reducing the kernel options for modules that will never ever be used on an UP board?
I was able to get the compile time down from an hour to about 5 minutes inside of a VM on an MBP.
[ts.config.txt](https://github.com/emutex/ubilinux-kernel/files/1703940/ts.config.txt)

**Comment by jbeta** [comment]
Hi @Thinstation,

Thanks for sharing! Indeed there's lots of room for shrinking the ubilinux kernel. We purposely aimed to stay as close as possible to a stock Debian kernel config to maximize portability, since the UP boards aren't necessarily the only target platform.

If you would like to post your streamlined config where others users can benefit from it, I'd suggest the UP community wiki:
https://wiki.up-community.org/Compile_ubilinux_kernel_from_source
Or I can add it for you (with your permission).

Thank you!

**Comment by Thinstation** [comment]
Yeah, place it wherever you like, I have it in a port within my own project. Might evolve it .... Not sure about all the goals your trying to meet with your project, but others could probably use that config.

**Comment by jbeta** [comment]
Added a link - thank you!
